### ISSUE TITLE
Missing method definition: ReadRemoteString().

### ISSUE THREAD

**Issue by Brunocg** [ReClassNET/ReClass.NET-UnrealEngineClassesPlugin#3]
The below error appear while compiling UnrealEngineClassesPlugin
'RemoteProcess' does not contain a definition for 'ReadRemoteString' and no accessible extension method 'ReadRemoteString' accepting a first argument of type 'RemoteProcess' could be found (are you missing a using directive or an assembly reference?)

**Comment by cocoon** [comment]
it was moved out with this commit:
https://github.com/ReClassNET/ReClass.NET/commit/e968a2908f3f53a42be61a27a61552f0e91fdc4a#diff-56ab2a0c17dd1e29df0ec0300c87e39aa6159f260119206d62e19fb3b2de6909R90

need to add:

```
using ReClassNET.Extensions;
```

and

```
...
var text = context.Process.ReadRemoteString(ptr, Encoding.Unicode, length);
...
```

Compiles OK and loads now.
